-- V10__code_in_japanese.sql

CREATE TABLE code_review_exercises (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title                   VARCHAR(200) NOT NULL,
    title_jp                VARCHAR(200),
    exercise_type           VARCHAR(30) NOT NULL,
    code_context            VARCHAR(30) NOT NULL,
    difficulty              VARCHAR(20) NOT NULL,
    code_snippet            TEXT,
    code_language           VARCHAR(30),
    scenario                TEXT NOT NULL,
    scenario_jp             TEXT,
    expected_review_level   VARCHAR(20),
    technical_issues        JSONB,
    model_answer            TEXT,
    model_answer_explanation TEXT,
    key_phrases             JSONB,
    avoid_phrases           JSONB,
    technical_terms_jp      JSONB,
    pr_template             JSONB,
    commit_rule             JSONB,
    cultural_note           TEXT,
    xp_reward               INTEGER NOT NULL DEFAULT 50,
    published               BOOLEAN NOT NULL DEFAULT false,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE code_exercise_attempts (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID NOT NULL REFERENCES users(id),
    exercise_id                 UUID NOT NULL REFERENCES code_review_exercises(id),
    exercise_type               VARCHAR(30) NOT NULL,
    user_response               TEXT NOT NULL,
    technical_accuracy_score    INTEGER NOT NULL,
    japanese_quality_score      INTEGER NOT NULL,
    professional_tone_score     INTEGER NOT NULL,
    structure_score             INTEGER NOT NULL,
    team_communication_score    INTEGER NOT NULL,
    overall_score               INTEGER NOT NULL,
    violations                  JSONB,
    commit_analysis             JSONB,
    feedback                    TEXT,
    time_spent_seconds          INTEGER NOT NULL DEFAULT 0,
    attempted_at                TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE code_japanese_progress (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES users(id),
    exercise_type           VARCHAR(30) NOT NULL,
    exercises_completed     INTEGER NOT NULL DEFAULT 0,
    total_score             INTEGER NOT NULL DEFAULT 0,
    average_score           INTEGER NOT NULL DEFAULT 0,
    best_score              INTEGER NOT NULL DEFAULT 0,
    current_streak          INTEGER NOT NULL DEFAULT 0,
    recurring_violations    JSONB,
    last_activity_at        TIMESTAMP,
    UNIQUE(user_id, exercise_type)
);

CREATE INDEX idx_code_exercises_type ON code_review_exercises(exercise_type, difficulty);
CREATE INDEX idx_code_exercises_context ON code_review_exercises(code_context, published);
CREATE INDEX idx_code_attempts_user ON code_exercise_attempts(user_id);
CREATE INDEX idx_code_attempts_exercise ON code_exercise_attempts(exercise_id);
CREATE INDEX idx_code_progress_user ON code_japanese_progress(user_id);

-- Seed data: 12 exercises covering developer workflows in Japanese
INSERT INTO code_review_exercises (title, title_jp, exercise_type, code_context, difficulty, code_snippet, code_language, scenario, scenario_jp, expected_review_level, technical_issues, model_answer, model_answer_explanation, key_phrases, avoid_phrases, technical_terms_jp, pr_template, commit_rule, cultural_note, xp_reward, published)
VALUES
('Review: Redundant null check after Optional', 'レビュー：Optional後の不要なnullチェック',
 'CODE_REVIEW', 'BACKEND_JAVA', 'N3',
 'Optional<User> userOpt = userRepository.findById(id);\nif (userOpt.isPresent()) {\n    User user = userOpt.get();\n    if (user != null) {\n        return user.getName();\n    }\n}\nreturn "unknown";',
 'java',
 'You are reviewing a junior developer''s PR. The code has a redundant null check after Optional.get(). Write a constructive review comment in Japanese.',
 'ジュニア開発者のPRをレビューしています。Optional.get()の後に冗長なnullチェックがあります。建設的なレビューコメントを日本語で書いてください。',
 'SUGGESTION', '["redundant null check", "Optional misuse", "can simplify with orElse"]',
 '細かい点ですが、Optional.get()の戻り値はnullにならないため、内側のnullチェックは不要かと思います。orElse("unknown")を使うとよりシンプルに書けるかもしれません。ご検討いただけると幸いです。',
 'Starts with cushion word, explains reason, offers alternative, ends with soft request.',
 '["細かい点ですが", "不要かと思います", "シンプルに書ける", "ご検討いただけると"]',
 '["直してください", "間違っています", "ダメです", "nullチェックいらない"]',
 '["nullチェック", "戻り値", "冗長", "簡潔に"]',
 NULL, NULL,
 'In Japanese code reviews, always start with a cushion word when pointing out issues to junior developers.',
 75, true),

('Review: SQL injection vulnerability', 'レビュー：SQLインジェクション脆弱性',
 'CODE_REVIEW', 'BACKEND_JAVA', 'N2',
 'String query = "SELECT * FROM users WHERE email = ''" + email + "''";\nStatement stmt = connection.createStatement();\nResultSet rs = stmt.executeQuery(query);',
 'java',
 'You found a critical SQL injection vulnerability. This is a blocking issue. Write the review comment in Japanese.',
 'クリティカルなSQLインジェクション脆弱性を発見しました。マージ前に修正が必要です。日本語でレビューコメントを書いてください。',
 'MUST_FIX', '["SQL injection", "string concatenation in query", "should use PreparedStatement"]',
 'セキュリティ上の重要な指摘です。文字列結合によるSQL構築はSQLインジェクションの脆弱性になります。PreparedStatementのパラメータバインディングをご利用ください。修正をお願いいたします。',
 'Even for critical issues, maintain politeness.',
 '["セキュリティ上の", "脆弱性", "修正をお願いいたします", "パラメータバインディング"]',
 '["ダメです", "これはひどい", "なんでこんなコード", "修正しろ"]',
 '["SQLインジェクション", "脆弱性", "パラメータバインディング", "PreparedStatement"]',
 NULL, NULL,
 'For security issues, Japanese dev culture still requires politeness but allows more direct language.',
 100, true),

('Write a PR description for authentication feature', '認証機能のPR説明文を作成する',
 'PR_WRITING', 'BACKEND_JAVA', 'N3',
 NULL, NULL,
 'You implemented JWT authentication with refresh token rotation. Write the PR description in Japanese.',
 'JWT認証機能を実装しました。標準テンプレートに従ってPR説明文を日本語で書いてください。',
 NULL, '["JWT implementation", "refresh token rotation", "security headers"]',
 '## 背景\nセキュリティ要件として、ステートレスな認証基盤の構築が必要でした。\n\n## 変更内容\n- JWT認証フィルターの実装\n- リフレッシュトークンのローテーション機能追加\n\n## 影響範囲\n- 全認証済みエンドポイントに影響\n\n## テスト計画\n- ユニットテスト：JwtServiceTest, AuthFilterTest',
 'A good Japanese PR uses clear sections with headers and bullet points.',
 '["背景", "変更内容", "影響範囲", "テスト計画", "実装", "追加"]',
 '["English section headers", "too vague descriptions"]',
 '["認証", "ステートレス", "リフレッシュトークン", "エンドポイント"]',
 '{"requiredSections":["BACKGROUND","CHANGES","IMPACT","TEST_PLAN"],"sectionHints":{"BACKGROUND":"Why was this needed?","CHANGES":"What changed?","IMPACT":"What areas affected?","TEST_PLAN":"How tested?"},"sectionKeyPhrases":{"BACKGROUND":["要件","必要"],"CHANGES":["実装","追加"],"IMPACT":["影響","範囲"],"TEST_PLAN":["テスト","確認"]},"minSections":4,"requiresJapaneseOnly":true}',
 NULL,
 'Japanese PR descriptions follow a structured template. Headers are always in Japanese.',
 80, true),

('Write a commit message for adding user registration', 'ユーザー登録機能追加のコミットメッセージ',
 'COMMIT_MESSAGE', 'BACKEND_JAVA', 'N4',
 NULL, NULL,
 'You implemented user registration with email validation. Write the commit message in Japanese.',
 'メールバリデーション付きのユーザー登録機能を実装しました。コミットメッセージを書いてください。',
 NULL, NULL,
 'feat(auth): ユーザー登録機能の追加（メールバリデーション付き）',
 'Japanese commit messages use noun ending (体言止め).',
 '["機能", "追加", "ユーザー登録"]',
 '["しました", "追加した", "します"]',
 '["ユーザー登録", "バリデーション", "認証"]',
 NULL,
 '{"expectedPrefix":"FEAT","requireTaigenDome":true,"maxLength":72,"requireScope":true,"expectedScope":"auth","forbiddenPatterns":["しました","します","した","できた"],"goodExamples":["feat(auth): ユーザー登録機能の追加"],"badExamples":["feat(auth): ユーザー登録機能を追加しました"]}',
 'In Japanese dev teams, commit messages use 体言止め — ending with a noun rather than a conjugated verb.',
 60, true),

('Write a commit message for fixing a null pointer', 'NullPointerException修正のコミットメッセージ',
 'COMMIT_MESSAGE', 'BACKEND_JAVA', 'N4',
 NULL, NULL,
 'You fixed a NullPointerException when user has no profile set. Write the commit message.',
 'プロフィール未設定時のNullPointerExceptionを修正しました。コミットメッセージを書いてください。',
 NULL, NULL,
 'fix(user): プロフィール未設定時のNullPointerException修正',
 'Bug fix commits are concise. State the condition and the fix outcome.',
 '["修正", "未設定時", "NullPointerException"]',
 '["修正しました", "バグを直した", "fixed"]',
 '["NullPointerException", "プロフィール", "未設定"]',
 NULL,
 '{"expectedPrefix":"FIX","requireTaigenDome":true,"maxLength":72,"requireScope":true,"expectedScope":"user","forbiddenPatterns":["しました","した","直した","修正した"],"goodExamples":["fix(user): プロフィール未設定時のNPE修正"],"badExamples":["fix: NPEを修正しました"]}',
 'NullPointerException can be abbreviated to NPE in Japanese dev context.',
 50, true),

('Write a bug report for a login failure', 'ログイン失敗のバグレポート',
 'BUG_REPORT', 'BACKEND_JAVA', 'N3',
 NULL, NULL,
 'Login fails intermittently with 500 error when session cache is cold. Write a structured bug report in Japanese.',
 'セッションキャッシュ未起動時にログインが500エラーで失敗します。バグレポートを日本語で書いてください。',
 NULL, '["session cache cold start", "500 error", "intermittent failure"]',
 '## 概要\nセッションキャッシュ未起動時にログインが500エラーで失敗する\n\n## 再現手順\n1. Redisキャッシュを再起動する\n2. ログインを試行する\n3. 500エラーが返される\n\n## 期待結果\nキャッシュミス時はDBにフォールバックしてログイン成功\n\n## 実際の結果\nNullPointerExceptionが発生し500エラー',
 'Japanese bug reports follow strict template: Overview, Steps, Expected, Actual.',
 '["概要", "再現手順", "期待結果", "実際の結果"]',
 '["何かおかしい", "バグってる", "壊れてます"]',
 '["セッションキャッシュ", "フォールバック", "NullPointerException"]',
 NULL, NULL,
 'Japanese bug reports value precision and structure. Never blame individuals.',
 80, true),

('Review: N+1 query in loop', 'レビュー：ループ内のN+1クエリ',
 'CODE_REVIEW', 'BACKEND_JAVA', 'N3',
 'List<Order> orders = orderRepository.findAll();\nfor (Order order : orders) {\n    Customer customer = customerRepository.findById(order.getCustomerId());\n    order.setCustomerName(customer.getName());\n}',
 'java',
 'You notice an N+1 query problem. Suggest a batch fetch approach politely.',
 'N+1クエリの問題を発見しました。バッチ取得のアプローチを丁寧に提案してください。',
 'SUGGESTION', '["N+1 query", "batch fetch", "JOIN or IN clause"]',
 'パフォーマンスの観点で一点提案です。ループ内で顧客を1件ずつ取得しているため、N+1問題が発生する可能性があります。バッチ取得はいかがでしょうか。',
 'Context + problem + alternative + soft hedge.',
 '["パフォーマンスの観点", "N+1問題", "バッチ取得", "いかがでしょうか"]',
 '["遅いです", "N+1だ", "修正してください"]',
 '["N+1問題", "バッチ取得", "パフォーマンス"]',
 NULL, NULL,
 'For performance suggestions, acknowledge current approach might work for small data.',
 75, true),

('Propose a caching strategy in standup', 'スタンダップでキャッシュ戦略を提案する',
 'TECH_DISCUSSION', 'BACKEND_JAVA', 'N3',
 NULL, NULL,
 'Propose adding Redis caching for a high-traffic endpoint during standup.',
 'チームスタンダップでRedisキャッシュの導入を提案してください。',
 NULL, '["Redis caching", "high traffic", "TTL strategy"]',
 'ユーザープロフィールのエンドポイントについて、Redisキャッシュの導入を検討してはいかがでしょうか。レスポンスタイムの改善が見込めると考えています。',
 'Technical proposals should present data and offer to own the work.',
 '["検討してはいかがでしょうか", "と考えています", "いかがでしょうか"]',
 '["やるべき", "絶対必要", "俺がやる"]',
 '["キャッシュ", "レスポンスタイム", "TTL"]',
 NULL, NULL,
 'In standups, proposals should be framed as suggestions, not declarations.',
 70, true),

('Write a commit for extracting a service class', 'サービスクラス抽出のコミットメッセージ',
 'COMMIT_MESSAGE', 'BACKEND_JAVA', 'N4',
 NULL, NULL,
 'You refactored a controller by extracting logic into UserService. Write the commit message.',
 'コントローラーからUserServiceにロジックを抽出しました。コミットメッセージを書いてください。',
 NULL, NULL,
 'refactor(user): ビジネスロジックのUserServiceへの抽出',
 'Refactor commits use noun endings like 抽出, 分離, 統合.',
 '["リファクタリング", "抽出", "UserService"]',
 '["抽出しました", "移動した", "refactored"]',
 '["ビジネスロジック", "サービスクラス", "抽出"]',
 NULL,
 '{"expectedPrefix":"REFACTOR","requireTaigenDome":true,"maxLength":72,"requireScope":true,"expectedScope":"user","forbiddenPatterns":["しました","した","移した"],"goodExamples":["refactor(user): ビジネスロジックのUserServiceへの抽出"],"badExamples":["refactor: ロジックを移しました"]}',
 'Refactoring commits use standard noun endings.',
 50, true),

('Write a PR for fixing a race condition', '競合状態修正のPR説明文',
 'PR_WRITING', 'BACKEND_JAVA', 'N2',
 NULL, NULL,
 'You fixed a race condition in payment processing. Write the PR description in Japanese.',
 '決済処理の競合状態を修正しました。PR説明文を日本語で書いてください。',
 NULL, '["race condition", "double debit", "pessimistic locking"]',
 '## 背景\n決済処理で二重引き落としが発生する競合状態が報告されました。\n\n## 変更内容\n- 悲観的ロックの導入\n- 二重引き落とし検知の追加\n\n## 影響範囲\n- PaymentService\n\n## テスト計画\n- 並行テストで二重引き落としが発生しないことを確認',
 'Bug fix PRs need root cause section.',
 '["背景", "変更内容", "影響範囲", "テスト計画", "競合状態"]',
 '["I fixed...", "It works now"]',
 '["競合状態", "二重引き落とし", "悲観的ロック"]',
 '{"requiredSections":["BACKGROUND","CHANGES","IMPACT","TEST_PLAN"],"sectionHints":{"BACKGROUND":"Include root cause","CHANGES":"List specific changes","IMPACT":"Performance implications","TEST_PLAN":"Concurrency testing"},"sectionKeyPhrases":{"BACKGROUND":["報告","発生"],"CHANGES":["導入","追加"],"IMPACT":["影響","パフォーマンス"],"TEST_PLAN":["確認","テスト"]},"minSections":4,"requiresJapaneseOnly":true}',
 NULL,
 'For bug fix PRs, transparency about performance impact builds trust.',
 100, true),

('Write praise for elegant error handling', 'エレガントなエラーハンドリングへの称賛',
 'CODE_REVIEW', 'BACKEND_JAVA', 'N4',
 '@ExceptionHandler(BusinessException.class)\npublic ResponseEntity<ApiError> handleBusiness(BusinessException ex) {\n    ApiError error = ApiError.of(ex.getCode(), ex.getMessage());\n    log.warn("Business error: {}", ex.getMessage());\n    return ResponseEntity.status(ex.getHttpStatus()).body(error);\n}',
 'java',
 'A colleague implemented clean error handling. Write a positive review comment in Japanese.',
 '同僚がきれいなエラーハンドリングを実装しました。褒めるレビューコメントを書いてください。',
 'PRAISE', NULL,
 'エラーハンドリングの設計がとても分かりやすいですね。参考にさせていただきます！',
 'Praise should be specific about what is good.',
 '["分かりやすい", "素晴らしい", "参考にさせていただきます"]',
 '["LGTM", "いいね", "OK"]',
 '["エラーハンドリング", "ビジネス例外", "マッピング"]',
 NULL, NULL,
 'PRAISE comments are valued for team building. Be specific about WHY something is good.',
 50, true),

('Ask for help debugging a memory leak', 'メモリリークのデバッグで助けを求める',
 'TECH_DISCUSSION', 'BACKEND_JAVA', 'N3',
 NULL, NULL,
 'You need to ask a senior developer for help with a memory leak investigation.',
 'メモリリークの調査でシニア開発者に助けを求めてください。',
 NULL, '["memory leak", "heap dump analysis", "need help"]',
 'お忙しいところ恐れ入りますが、メモリリークの件でご相談させていただけないでしょうか。2日間調査しておりますが原因特定に至っておりません。',
 'Asking for help requires acknowledging their busy schedule and showing your effort.',
 '["恐れ入りますが", "ご相談させていただけないでしょうか", "至っておりません"]',
 '["教えて", "分からない", "手伝って", "助けてください"]',
 '["メモリリーク", "ヒープダンプ", "解析"]',
 NULL, NULL,
 'Show you tried first, be specific about what help you need, give flexibility on timing.',
 70, true);
